# Generated by Django 3.1.5 on 2021-01-15 18:58

from django.db import migrations
from django.core.management import call_command

def forwards_func(apps, schema_editor):
    call_command('loaddata','./backend/main_data/todo.json', verbosity=2)

def reverse_func(apps, schema_editor):
    ToDo = apps.get_model('todo','ToDo')
    ids = range(1,11)
    ToDo.objects.filter(id__in=ids).delete()
    call_command('sqlsequencereset')
   
    print('reverse')

class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func, elidable=False)
    ]

